//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COMessengerClient.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500,1000")]
        public global::COMessengerClient.Properties.WindowSize MainWindowSize {
            get {
                return ((global::COMessengerClient.Properties.WindowSize)(this["MainWindowSize"]));
            }
            set {
                this["MainWindowSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Verdana,13,96,96,96")]
        public global::COMessengerClient.Properties.FontInfo NewMessageFont {
            get {
                return ((global::COMessengerClient.Properties.FontInfo)(this["NewMessageFont"]));
            }
            set {
                this["NewMessageFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Segoe UI,11,96,96,96")]
        public global::COMessengerClient.Properties.FontInfo ChatBoxFont {
            get {
                return ((global::COMessengerClient.Properties.FontInfo)(this["ChatBoxFont"]));
            }
            set {
                this["ChatBoxFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseCurrentWindowsAccount {
            get {
                return ((bool)(this["UseCurrentWindowsAccount"]));
            }
            set {
                this["UseCurrentWindowsAccount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Default)")]
        public global::System.Globalization.CultureInfo UserCultureUIInfo {
            get {
                return ((global::System.Globalization.CultureInfo)(this["UserCultureUIInfo"]));
            }
            set {
                this["UserCultureUIInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserLogin {
            get {
                return ((string)(this["UserLogin"]));
            }
            set {
                this["UserLogin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserPassword {
            get {
                return ((string)(this["UserPassword"]));
            }
            set {
                this["UserPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserDomain {
            get {
                return ((string)(this["UserDomain"]));
            }
            set {
                this["UserDomain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Server {
            get {
                return ((string)(this["Server"]));
            }
            set {
                this["Server"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Port {
            get {
                return ((string)(this["Port"]));
            }
            set {
                this["Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoSignIn {
            get {
                return ((bool)(this["AutoSignIn"]));
            }
            set {
                this["AutoSignIn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFF0F8FF")]
        public global::System.Windows.Media.Color IncomingMessageBackgroundColor1 {
            get {
                return ((global::System.Windows.Media.Color)(this["IncomingMessageBackgroundColor1"]));
            }
            set {
                this["IncomingMessageBackgroundColor1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFF0F8FF")]
        public global::System.Windows.Media.Color IncomingMessageBackgroundColor2 {
            get {
                return ((global::System.Windows.Media.Color)(this["IncomingMessageBackgroundColor2"]));
            }
            set {
                this["IncomingMessageBackgroundColor2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("35")]
        public double IncomeLeftIndent {
            get {
                return ((double)(this["IncomeLeftIndent"]));
            }
            set {
                this["IncomeLeftIndent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public double IncomeRightIndent {
            get {
                return ((double)(this["IncomeRightIndent"]));
            }
            set {
                this["IncomeRightIndent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public double BothBottomIndent {
            get {
                return ((double)(this["BothBottomIndent"]));
            }
            set {
                this["BothBottomIndent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double BothTopIndent {
            get {
                return ((double)(this["BothTopIndent"]));
            }
            set {
                this["BothTopIndent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("35,0,100,15")]
        public global::System.Windows.Thickness IncomePadding {
            get {
                return ((global::System.Windows.Thickness)(this["IncomePadding"]));
            }
            set {
                this["IncomePadding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public double ContactListRowHeight {
            get {
                return ((double)(this["ContactListRowHeight"]));
            }
            set {
                this["ContactListRowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#1000FF00")]
        public global::System.Windows.Media.Color OutcomingMessageBackgroundColor1 {
            get {
                return ((global::System.Windows.Media.Color)(this["OutcomingMessageBackgroundColor1"]));
            }
            set {
                this["OutcomingMessageBackgroundColor1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#1000FF00")]
        public global::System.Windows.Media.Color OutcomingMessageBackgroundColor2 {
            get {
                return ((global::System.Windows.Media.Color)(this["OutcomingMessageBackgroundColor2"]));
            }
            set {
                this["OutcomingMessageBackgroundColor2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100,0,20,15")]
        public global::System.Windows.Thickness OutcomePadding {
            get {
                return ((global::System.Windows.Thickness)(this["OutcomePadding"]));
            }
            set {
                this["OutcomePadding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SavePassword {
            get {
                return ((bool)(this["SavePassword"]));
            }
            set {
                this["SavePassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sound\\newmsg.wav")]
        public string SoundFileNewMessage {
            get {
                return ((string)(this["SoundFileNewMessage"]));
            }
            set {
                this["SoundFileNewMessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HideOnClose {
            get {
                return ((bool)(this["HideOnClose"]));
            }
            set {
                this["HideOnClose"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public global::System.Windows.GridLength ContactListWidth {
            get {
                return ((global::System.Windows.GridLength)(this["ContactListWidth"]));
            }
            set {
                this["ContactListWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public double AvatarHeightContactList {
            get {
                return ((double)(this["AvatarHeightContactList"]));
            }
            set {
                this["AvatarHeightContactList"] = value;
            }
        }
    }
}
